### ISSUE TITLE
Feature-parity of the Dolmen frontend

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#682]
- [x] Support for semantic triggers #681 
- [x] Support for theory extensions #662 
- [x] Support for `check_sat` #660 
- [x] Support for `(check-sat-assuming)` #695

**Comment by bclement-ocp** [comment]
As far as I know, this is done :tada:
