### ISSUE TITLE
Refactoring the output channels

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#785]
The current situation of the output management in AE is a bit of a mess.

Basically, the Alt-Ergo library should never print anything by itself. Such behaviour isn't expected from a library....
In my opinion, the library can only produce `Logs` sources to report debugging information on the diagnostic channel.

The Alt-Ergo binary prints results (answer, models and unsat core) on the regular output.

- [x] Removing useless output channels to fit with the SMT standard using only two channels (`regular` and `diagnostic`). See #782 
- [x] The Ocplib-simplex library shouldn't use the `App` level or set any level on its sources.
- [x] The Alt-Ergo library doesn't print any result by itself. In particular, we have to refactor the frontend of the SMT solver.
- [ ] Using Logs and sources everywhere in the Alt-Ergo library.
- [ ] Move the `module Output` from `options.ml` to the Alt-Ergo binary.

**Comment by Halbaroth** [comment]
As we decided during the last dev meeting, I tried to rewrite #1068 (which adds logs library) in order to implement the current `Printer` module. The idea was to limit as much as possible the modifications to this module. In particular, I tried to preserve as much as possible the current API of `Printer`. Unfortunately, it seems there is no way to reimplement `print_std`, `print_err`, ... without breaking their API. The issue comes from the fact these functions are variadic. For instance, if we want to implement `print_dbg` with `Logs.debug (fun k -> k ...)`, we need to feed the continuation `k` with the variadic arguments of `print_dbg`. I and Vincent did not find a hack to work around this issue.

**Comment by bclement-ocp** [comment]
Ah duh. Yeah I don't think we can preserve the current API then :cry:
