### ISSUE TITLE
Clean-up documentation

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#788]
This issue follows the clean-up of the documentation.

- [ ] Porting the Sphinx documentation to Odoc format.
- [ ] Write a complete ebnf description of the Alt-Ergo native language. I suggest to use the new Dolmen parser as reference.
- [ ] Use `highlight.js` to highlight both AE and SMT-LIB sources
- [ ] Use `mpx` to run cram task in the documentation. This feature prevents to deploy documentations with invalid commands.
